[package]
name = "seq"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
description = "print a sequence of numbers"
license = "GPL-3.0-only"

[dependencies]
anyhow = "1.0.33"
